version: "3"

services:
        nginx:
                build: requirements/nginx/
                container_name: nginx
                restart: always
                ports:
                       - "443:443"
                networks:
                       - nade_network
                #depends on:
                #       - wordpress
                volumes:
                       - website:/var/www/html         
        mariadb:
                container_name: mariadb
                build: 
                      requirements/mariadb/
                volumes:
                        - database:/var/www/html
                expose:
                        - "3306"
                networks:
                        - nade_network
                restart: always
                environment:
                        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
                        MARIADB_DATABASE: ${MARIADB_DATABASE}
                        MARIADB_MYSQL_LOCALHOST_USER: ${MARIADB_MYSQL_LOCALHOST_USER}
                        MARIADB_PASSWORD: ${MARIADB_PASSWORD}

        #wordpress:
                depends_on:
                        - mariadb
                build:
                        requirements/wordpress/
                container_name: wordpress
                volumes:
                       - wordpress:/var/www/html
                expose:
                        - "9000"
                networks:
                        - nade_network
                environment:
                      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
                      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
                      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
                      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

volumes:
  website:
    driver_opts:
      type: none
      device: /home/nade-la-/data/website
      o: bind
  database:
    driver_opts:
      type: none
      device: /home/nade-la-/data/database
      o: bind

networks:
  nade_network:             
