version: "3"

services:
        mariadb:
                container_name: mariadb
                build: 
                       requirements/mariadb/
                volumes:
                        - database:/var/lib/mysql
                expose:
                        - "3306"
                networks:
                        - nade_network
                restart: always
                environment:
                        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
                        MARIADB_DATABASE: ${MARIADB_DATABASE}
                        MARIADB_USER: ${MARIADB_USER}
                        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        
        wordpress:
                depends_on:
                        - mariadb
                image: wordpress
                build:
                        requirements/wordpress/
                container_name: wordpress
                volumes:
                        - website:/var/www/html
                expose:
                        - "9000"
                networks:
                        - nade_network
                environment:
                        WORDPRESS_DB_HOST: mariadb
                        MARIADB_DATABASE: ${MARIADB_DATABASE}
                        MARIADB_USER: ${MARIADB_USER}
                        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
                        WORDPRESS_DB_TITLE: ${WORDPRESS_DB_TITLE}
                        WORDPRESS_DB_ADMIN_EMAIL: ${WORDPRESS_DB_ADMIN_EMAIL}
                        WORDPRESS_DB_ADMIN_PWD: ${WORDPRESS_DB_ADMIN_PWD}
                        WORDPRESS_DB_ADMIN: ${WORDPRESS_DB_ADMIN}
                        DOMAIN_NAME: ${DOMAIN_NAME}
                        W_USER: ${W_USER}
                        W_PWD: ${W_PWD}
                        W_EMAIL: ${W_EMAIL}
        nginx:
                build: requirements/nginx/
                container_name: nginx
                restart: always
                ports:
                       - "443:443"
                networks:
                       - nade_network
                depends_on:
                       - wordpress
                volumes:
                       - website:/var/www/html         
        

volumes:
  website:
    driver_opts:
      type: none
      device: /home/nade-la-/data/website
      o: bind

  database:
    driver_opts:
      type: none
      device: /home/nade-la-/data/database
      o: bind

networks:
  nade_network:             
