version: "3"

services:
        nginx:
                build: requirements/nginx/
                container_name: nginx
                restart: always
                ports:
                       - "443:443"
                networks:
                       - nade_network
                depends_on:
                       - wordpress
                volumes:
                       - website:/var/www/html         
        
        mariadb:
                container_name: mariadb
                build: 
                       requirements/mariadb/
                volumes:
                        - database:/var/lib/mysql
                expose:
                        - "3306"
                networks:
                        - nade_network
                restart: always
                environment:
                        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
                        MARIADB_DATABASE: ${MARIADB_DATABASE}
                        MARIADB_USER: ${MARIADB_USER}
                        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        
        wordpress:
                depends_on:
                        - mariadb
                image: wordpress
                build:
                        requirements/wordpress/
                container_name: wordpress
                volumes:
                        - website:/var/www/html
                expose:
                        - "9000"
                networks:
                        - nade_network
                environment:
                        WORDPRESS_DB_HOST: mariadb
                        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
                        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
                        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME} 
                        WORDPRESS_DB_TITLE: ${WORDPRESS_DB_TITLE}

volumes:
  website:
    driver_opts:
      type: none
      device: /home/nade-la-/data/website
      o: bind

  database:
    driver_opts:
      type: none
      device: /home/nade-la-/data/database
      o: bind

networks:
  nade_network:             
